describe("time_math", function()
    local TimeMath = require("src.utils.time_math")

    describe("parseTime", function()
        it("parses 9am as 9:00", function()
            local hour, min, ampm = TimeMath.parseTime("9am")
            assert.are_equal(9, hour)
            assert.are_equal(0, min)
            assert.are_equal("am", ampm)
        end)

        it("parses 5:30pm as 17:30", function()
            local hour, min, ampm = TimeMath.parseTime("5:30pm")
            assert.are_equal(5, hour)
            assert.are_equal(30, min)
            assert.are_equal("pm", ampm)
        end)

        it("parses 14:30 as 14:30 (24h)", function()
            local hour, min, ampm = TimeMath.parseTime("14:30")
            assert.are_equal(14, hour)
            assert.are_equal(30, min)
            assert.is_nil(ampm)
        end)
    end)

    describe("parseDuration", function()
        it("parses 30m as 30 minutes", function()
            local secs = TimeMath.parseDuration("30m")
            assert.are_equal(1800, secs)
        end)

        it("parses 2h as 2 hours", function()
            local secs = TimeMath.parseDuration("2h")
            assert.are_equal(7200, secs)
        end)

        it("parses 1h30m as 90 minutes", function()
            local secs = TimeMath.parseDuration("1h30m")
            assert.are_equal(5400, secs)
        end)
    end)

    describe("addDuration", function()
        it("adds 2 hours to 9am", function()
            local result = TimeMath.addDuration("9am", "2h")
            assert.is_true(result:match("11:") ~= nil)
            assert.is_true(result:match("AM") ~= nil)
        end)

        it("wraps day: 11pm + 2h = 1am", function()
            local result = TimeMath.addDuration("11pm", "2h")
            assert.is_true(result:match("1:") ~= nil)
            assert.is_true(result:match("AM") ~= nil)
        end)
    end)
end)
